name: Send Email On Tag Creation

on:
  create:

jobs:
  send_email:
    if: ${{ contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Simulate sending email
        run: |
          echo "📧 Simulated sending email for tag: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "URL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
