
name: Notify Slack of New Deployment

on:
  deployment:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.7.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_ACCESS_TOKEN }}
          slack-channel: ${{ vars.SLACK_CHANNEL }}
          slack-text: |
            Hi there 👋🏻
            A new deployment has been created in the ${{ github.repository }} /
            repository on the `${{ github.ref }}` branch/tag \
            (SHA: `${{ github.sha }}`).
