name: Notify Slack of Deployment Status

on:
  deployment_status:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.7.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_ACCESS_TOKEN }}
          slack-channel: ${{ vars.SLACK_CHANNEL }}
          slack-text: |
            The deployment in the ${{ github.repository }} repository on \
            the `${{ github.ref }}` branch/tag (SHA: `${{ github.sha }}`) \
            now has the status: `${{ github.event.deployment_status.state }}`.

