name: Deploy to Vercel on Push

on:
  push:
    branches: [main]

jobs:
  deploy_to_vercel:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Simulate deploy to Vercel
        run: |
          echo "🚀 Simulating Vercel deployment..."
          echo "Triggered by push to branch: ${{ github.ref_name }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Repository: ${{ github.repository }}"
