name: Deploy to Vercel on Push

on:
  # Will trigger the workflow whenever a commit is pushed to
  # the master branch
  push:
    branches: [master]

jobs:
  deploy_to_vercel:
    permissions: write-all
    runs-on: ubuntu-latest
    # Skips the job if the string "[skip ci]" is present in the 
    # commit message
    if: ${{ !contains(github.event.head_commit, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.12
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
