name: Send Release Email

on:
  # Will trigger the workflow when a new release is published 
  # in the repository
  release:
    types: [published]

jobs:
  send_release_email:
    runs-on: ubuntu-latest
    steps:
      # Sends an email using SMTP
      - name: Send email
        uses: dawidd6/action-send-mail@v3.8.0
        with:
          server_address: ${{ secrets.SERVER_ADDRESS }}
          server_port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Tag Created
          to: ${{ vars.EMAIL_RECIPIENTS }}
          from: ${{ vars.EMAIL_SENDER }}
          html_body: file://emails/new_release.html
