name: Mark Stale Branches

on:
  # Will trigger the workflow every day at 6am using a cron schedule
  schedule: 
    - cron: 0 6 * * *

jobs:
  mark_stale_branches:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # Action that goes through all branches and mark branches older 
      # than 30 days as stale
      - name: Mark Stale Branches
        uses: crs-k/stale-branches@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-delete: 90
